### ISSUE TITLE
Access vhost from the network.

### ISSUE THREAD

**Issue by kanglinyao** [cytopia/devilbox#120]
I am trying to use devilbox as a production server. I left the listening ip to blank so that all interfaces are listened.  How do I direct all access request to Wordpress site rather than the devilbox home page?

**Comment by cytopia** [comment]
@kanglinyao I personally would not use it or recommend it as a production server.

To access your Wordpress vhost with a real domain (e.g.: `my-wordpress.com`), you can use the following trick:

1. Set `TLD_SUFFIX=com`
2. Create your project folder by the name `my-wordpress`.
3. Set the DNS record of `my-wordpress.com` to the IP address of your devilbox server

However, once someone access the devilbox server by its IP address, he/she will always see the devilbox start page (because it is the default virtual host).

**Note:** You can also use any other made-up domain as well, as long as you have a DNS server within your LAN that controls the DNS records to that domain.

Let me know if the above works and then we can figure something out for getting the default vhost to not show up.

**Comment by kanglinyao** [comment]
May I ask how I change default devilbox address to something like localhost:8888 rather than just localhost. Could you also implement a way that people can assign the default vhost when the listening IP is accessed? That way people can work on the same project over at the same time on remote devilbox projects.

**Comment by cytopia** [comment]
@kanglinyao 
Please could you please create separate tickets if there are multiple requests.

I can definitely do the default port change. I will use this ticket for it.
So let's discuss other stuff in different tickets.

**Comment by kanglinyao** [comment]
I am sorry for posting in the wrong place. I have moved the feature request to a seperate ticket.

**Comment by cytopia** [comment]
@kanglinyao 

To access the devilbox from the network, you also have to change `LOCAL_LISTEN_ADDR=127.0.0.1:` to `LOCAL_LISTEN_ADDR=` in the `.env` file.

I will add that to the documentation as well.

For your other questions, we will continue in https://github.com/cytopia/devilbox/issues/121

**Comment by cytopia** [comment]
@kanglinyao 

For accessing the devilbox from other computers on your network, refer to: https://github.com/cytopia/devilbox/blob/master/docs/Configure.md#23-host-computer-listening-address

That explains it. If you find that documentation insufficient, please let me know and I will extend it.

**Comment by cytopia** [comment]
@kanglinyao for production usage see here.
Collective issue: https://github.com/cytopia/devilbox/issues/262

For accessing a shared Devilbox server see here: https://devilbox.readthedocs.io/en/latest/corporate-usage/shared-devilbox-server-in-lan.html
