### ISSUE TITLE
New logo and icons suggestion

### ISSUE THREAD

**Issue by maxencedubois** [cytopia/devilbox#131]
Hello,

I am a Devilbox user and I've seen on the to-do list in Contributing file that you were searching some help for better logos. I've tried to draw something that could suit well to any desktop (windows, macos and linux) with size variations. Could you tell me what you think of this proposal or suggest what could be done to make it as best as possible?

Thank you,

Maxence Dubois

[logo_proposal.zip](https://github.com/cytopia/devilbox/files/1352223/logo_proposal.zip)

**Comment by cytopia** [comment]
@maxencedubois Thank you very much for your logo pack :+1: .

I have look through it carefully. It is well designed and a good idea - even taken literally, but it does not really fit my personal taste. I would rather go with a more minimalist approach. Something like:

* Keep current type of colors: red, black and white (other shading of them is totally fine)
* Maybe 2d instead of 3d
* Should be recognizable, even if it is a small graphic.

---

But still, I think logos is a very personal taste thing and others might find it much better than the current logo. So this work will be appreciated and added to the **artwork** and might be scheduled for later voting anyway.

I also have just redesigned the artwork repository for the devilbox. **Please send a PR with your work there: https://github.com/devilbox/artwork/**

Here is how to do that exactly: https://github.com/devilbox/artwork/blob/master/CONTRIBUTING.md

I will close this ticket here, as the new repository will take care about it from now on.
