### ISSUE TITLE
Read-only file system in shared folder

### ISSUE THREAD

**Issue by mikados** [cytopia/devilbox#134]
Hi,

### my config:
```
- Latest devilbox
- php-fpm-7.1 + nginx-stable + mariadb-10.1
- Host: Windows 10 x64
- Docker version 17.09.0-ce build afdb6d4
- Docker-compose version 1.16.1 build 6d1ac219
```

### problem:
Everything works fine, but when trying to create a file from the httpd container it indicates the following error:

```
sh-4.2$ cd /shared/httpd/project1.demo/
sg-4.2$ touch demo.txt
touch: cannot touch 'demo.txt': Read-only file system
```

Why is the shared file system mounted read-only? Is it possible to write?

Thanks

**Comment by cytopia** [comment]
@mikados it looks like your are using an old version of the devilbox. Did you pull the latest updates from the master branch? It used to be read-only a while ago and has already been fixed.

Additional, please check [Requirements](https://github.com/cytopia/devilbox/blob/master/docs/README.md#4-requirements). Your Docker-compose version (`Docker-compose version 1.16.1 build 6d1ac219`) is too old. It requires `Docker Compose 1.9.0+`

See the [Docker Compose Documentation](https://docs.docker.com/compose/install/#install-compose) for how to quickly update it

**Comment by cytopia** [comment]
@mikados I will close this due to inactivity.

As already mentioned this problem has been fixed some time ago. Please use latest `master` branch and give it another shot. If you still encounter this problem, please Update Docker/Docker-compose to the above described minimum versions and provide your `.env` file as well as an extract from `docker-compose logs`
