### ISSUE TITLE
Production Suggestion

### ISSUE THREAD

**Issue by alivelimeli** [cytopia/devilbox#169]
Hello,

I like and use Devilbox on local development environment. I know its for local development but do you have a suggestion similar like devilbox to be used on production?

Thanks

**Comment by cytopia** [comment]
Hi,

I am not aware of anything similar (if it is about the features).

Apart from that you could always go with a custom `docker-compose.yml` file and use the official docker images of nginx and php-fpm.

However, I am currently working on making the devilbox docker images more robust with auto-rebuild every night in order to have all the latest patches applied.

The PHP-FPM 7.3 Image is already merged and offers different flavors (alpine vs debian and many modules vs less modules) that could also be used for production. Have a look at this one for example:

https://github.com/devilbox/docker-php-fpm-7.3

This will be included in the next release. Only thing that might prevent it, is a second `docker-compose.yml` that does not load the bundled intranet, logs and shell configs.

But, for now I would recommend to go with the official docker images as the devilbox images haven't had any security review nor automated security tests.

**Comment by cytopia** [comment]
@alivelimeli I will close this issue as I am not really aware of except for the official docker images and question has been answered as much as i could.

At the very beginning of next year I hopefully have time to set up a simple board so that questions like this will have a broader audience.

**Comment by cytopia** [comment]
@alivelimeli  New images have been built and will be security-checked via anchor.io: https://github.com/cytopia/devilbox/issues/191

**Comment by cytopia** [comment]
@alivelimeli 
Collective issue: https://github.com/cytopia/devilbox/issues/262
