### ISSUE TITLE
What stops using devilbox for production system

### ISSUE THREAD

**Issue by gowrav-vishwakarma** [cytopia/devilbox#188]
Hi,
devilbox is something a developer needs as must. But since it has everything needed to run things in proper way in containers, can it be used in production? if not what makes is not suitable for production, if not.

Can I do following:
creating vhosts with different tlds like xyz.com and abc.in
can each vhost can have its own php.ini settings

**Comment by cytopia** [comment]
@gowrav-vishwakarma you can read more here: https://github.com/cytopia/devilbox/issues/169

Once the new PHP container are in place it might be more suitable for production. I am currently also researching automated security testing for those images so it is made sure that at least the underlying software does not have any **known** flaws.

Apart from that I guess it is a matter of adoption. Once more people use it, more potential bugs can be found and then be fixed.

I myself am not *yet* using it for production and will still wait some more time for the actual v1.0 release (when i think it is rock-solid and stable).

**Comment by cytopia** [comment]
Different tld's per vhost are currently not supported and not be implemented within the next 6 months. I will therefore close this ticket. Feel free to add your request to the roadmap: https://github.com/cytopia/devilbox/issues/23

Once this is up for schedule I will re-open or create a new ticket.

**Comment by cytopia** [comment]
@gowrav-vishwakarma  New images have been built and will be security-checked via anchor.io: https://github.com/cytopia/devilbox/issues/191

**Comment by RoestVrijStaal** [comment]
Ok, so using devilbox for production is a future goal. Kinda heartbleeding because devilbox is such a solid solution.

What are -at the moment- my alternatives except reinventing the devilbox-wheel for my production environment?

**Comment by cytopia** [comment]
@RoestVrijStaal currently the *major* blocker is the mail catch-all. I have to re-configure it that you can have it run for development (as it does currently) and also to be able to disable it so that nothing is catched, but send (I think currently, once it is disabled, nothing is sent at all - I do need to double check this tough).

The second part is to have a `docker-compose.production.yml` which specifies the production PHP images.

Apart from that, what is stopping it:

Actually nothing, I just want to make double/triple sure that everything is configured in the safest possible way. Now that it is even possible to disable PHP modules during start-up, this is a next step towards production usage.

**Comment by cytopia** [comment]
@RoestVrijStaal @gowrav-vishwakarma 
Collective issue: https://github.com/cytopia/devilbox/issues/262
