### ISSUE TITLE
Working on nodejs projects 

### ISSUE THREAD

**Issue by dozzy100** [cytopia/devilbox#195]
How do you work on nodejs projects with files/folders on local/host machine?

**Comment by cytopia** [comment]
@dozzy100 how would you do it normally? Could you be a bit more specific

**Comment by dozzy100** [comment]
Normally with both node and project files available on my machine, I would just run the command, for eg:

node app.js 

to start the application. But using devilbox with node being inside the container and project files outside it, how do I use it?

**Comment by cytopia** [comment]
You can do both: Files are both inside as well as outside. There should not be a difference. Files you have on your local machine are just mounted into the container, so that they are available there additionally.

If you want to work inside the container use `./shell.sh` to enter it. It has all node binaries inside. Or you do it from the outside if you have node installed on your host system.

**Comment by dozzy100** [comment]
How will the local folders be mounted? I see mount settings for http, mysql, pgsql and mongo in the .env file. How do I specify which project folder to mount? Am I missing something obvious?

**Comment by cytopia** [comment]
Have a look at this video, it will cover all the basics and make it more understandable:  https://www.youtube.com/watch?v=reyZMyt2Zzo

**Comment by cytopia** [comment]
@dozzy100 does this answer your question?

**Comment by cytopia** [comment]
@dozzy100 I will close this. If you have a specific issue regarding your node project, feel free to re-open.

**Comment by Halfnium** [comment]
Dear Cytopia,

Perhaps dozzy100 is looking for some additional flexibility in using symlinks.  As the examples in the documentation show, many frameworks  / CMS tools require that nested folders contain the files to be served.  Devilbox allows this, of course.

However, suppose that you prefer to keep a project's files somewhere _outside_ of /home/devilbox/data/www, perhaps in /home/webprojects.  In that case, pointing to them via a symlink on htdocs does not work: Those project files reside outside of the mounted Docker volume, /shared/httpd.

Why keep projects "off to the side" instead of inside /home/devilbox?  One reason is self protection.  Suppose someday I decide to not use Devilbox further.  Without thinking carefully, I delete it by recursively removing /home/devilbox.  Oh no!  I have deleted all of my projects as well!  This I could avoid if I set up symlinks within devilbox for each "off to the side" project.  Better would be just one symlink off of /home/devilbox/data/www to /home/webprojects.

Another worry with local-development web stacks you have neutralized brilliantly with Devilbox's design.  I reinstall Linux (Ubuntu) frequently.  For convenience and (again) self-protection, I place user files in a partition of their own (/home), which I mount after the new OS installation works properly.

The next step has been to install an AMP stack.  (This step I gladly replace with Devilbox installation.)  Because 'root' owns the stack, I communicate with it via FTP.  Due to this workflow, I consider /home/webprojects to contain the "real" state of my project and /var/www (the default for Apache) to contain an "approximate" state.  I am responsible for synchronizing these.  I don'tj like this, but I have become accustomed to it.

So this second worry of mine: Installing that conventional AMP stack allows me to fool myself that I have synchronized the "real" and "approximate" states of my project when actually I have not.  Then, without thinking carefully, I reinstall Ubuntu and an AMPP stack with some new-version components.  My project doesn't work as observed just minutes before.  Is this due to the AMPP configuration change or due to my failure to synchronize?  What a waste of time and attention!

Contrast this to using Devilbox.  By experiment, I note that the user name "devilbox" temporarily becomes associated within the PHP container with my own UID and GID.  Hooray!  No more local FTP for me: I can edit my project and then serve & view it with just a browser refresh!

The only worry is that I will lose my discipline with this new workflow.  You have ruined me for using the non-containerized, conventional AMP stack.

**Comment by cytopia** [comment]
@Halfnium thanks for the detailed feedback. Please see my answer below:

> However, suppose that you prefer to keep a project's files somewhere outside of /home/devilbox/data/www, perhaps in /home/webprojects. In that case, pointing to them via a symlink on htdocs does not work: Those project files reside outside of the mounted Docker volume, /shared/httpd.

> Why keep projects "off to the side" instead of inside /home/devilbox? One reason is self protection. Suppose someday I decide to not use Devilbox further. Without thinking carefully, I delete it by recursively removing /home/devilbox. Oh no! I have deleted all of my projects as well! This I could avoid if I set up symlinks within devilbox for each "off to the side" project. Better would be just one symlink off of /home/devilbox/data/www to /home/webprojects.

These two problems can be resolved by just changing the `HTTPD_DOCROOT_DIR` value via `.env` file.
Simple set it to `HTTPD_DOCROOT_DIR=/home/webprojects` and you have all your data outside the devilbox git directory without having to use symlinks.
Maybe that feature is somewhere hidden within the bloat of the documentation ;-)

https://github.com/cytopia/devilbox/blob/master/docs/Configure.md#32-project-path



> ... So this second worry of mine: Installing that conventional AMP stack allows me to fool myself that I have synchronized the "real" and "approximate" states of my project when actually I have not. Then, without thinking carefully, I reinstall Ubuntu and an AMP stack with some new-version components. My project doesn't work as observed just minutes before. Is this due to the AMPP configuration change or due to my failure to synchronize? What a waste of time and attention! ...

I did not quite understand this part. What exactly is the problem here?

**Comment by Halfnium** [comment]
The second bit is actually a compliment, not a problem.  Good work, and thank you!

**Comment by cytopia** [comment]
Now I got it. So does the `HTTPD_DOCROOT_DIR` variable solve your problem?

**Comment by cytopia** [comment]
I will close this issue as it seems to be outdated. I will link it to a more complete issue here: https://github.com/cytopia/devilbox/issues/240

**Comment by cytopia** [comment]
@dozzy100 @Halfnium  NodeJS support is almost done. PR here: https://github.com/cytopia/devilbox/pull/449

All further information in above PR or this issue: https://github.com/cytopia/devilbox/issues/240

**Comment by cytopia** [comment]
https://devilbox.readthedocs.io/en/latest/examples/setup-reverse-proxy-nodejs.html
