### ISSUE TITLE
Vhost with www prefix

### ISSUE THREAD

**Issue by Jarco** [cytopia/devilbox#207]
Hello,

Is it possible to change the vhost template so it adds support for www. subdomains? I have lots of sites that are configured to redirect to www.sitename.ext and I cannot figure out how to serve them with devilbox correctly. 

I managed to do it for a separate domain with the vhost configuration per domain but would be thrilled if this could be automated in some way.

Docker version 18.02.0-ce, build fc4de447b5
OS: Manjaro Linux
docker-compose version 1.19.0

**Comment by cytopia** [comment]
@Jarco that is actually pretty simple.

Let's assume your project is called `sitename` (so you have created a directory `sitename/`) The vhost will be `sitename.loc` (if TLD_SUFFIX is `loc`).

In order to use `www.sitename.loc`, simply rename your folder to `www.sitename/`.

So some more examples here:

| directory | `TLD_SUFFIX` | vhost |
|---|---|---|
| `sitename/` | loc | `sitename.loc` |
| `www.sitename/` | loc | `www.sitename.loc` |
| `subdir.test/` | de | `subdir.test.de` |

**Comment by cytopia** [comment]
@Jarco does this resolve your issue?

**Comment by cytopia** [comment]
@Jarco  in-depth documentation available here: http://devilbox.readthedocs.io/en/documentation/tutorials/adding-subdomains.html
