### ISSUE TITLE
Running moodle in devilbox?

### ISSUE THREAD

**Issue by white-rabbit07** [cytopia/devilbox#215]
Hi. 
I think moodle 3.4.x would be great to run inside a devilbox!
Did anyone try this?

**Comment by white-rabbit07** [comment]
Yes, of course ... but the question is: When I change the database (let's say: ugrade mySQL 5.x --> 5.y) -- is all moodle-data lost or persistant? 
My hope is to find an "always-up-to-date"-solution for moodle; no matter on which server it runs. docker might be good for that if the upgrade (docker + moodle itself) worked.

**Comment by cytopia** [comment]
Data is persistent to each version of MySQL/MariaDB/PerconaDB.

If you want to test out a different version, just dump and import your data to the new version: http://devilbox.readthedocs.io/en/documentation/maintenance/backup-and-restore-mysql.html

Otherwise its not possible and not recommended, because data gets upgraded by MySQL and is not always be downgrade-able across versions. (e.g.: starting MySQL 5.5 with data from MySQL 5.7 will fail).

**Comment by white-rabbit07** [comment]
Ok, this case I have to use this howto:
https://docs.moodle.org/34/en/Moodle_migration
(still many steps to do manually ... I would still prefer a (semi-)**automatic** way to upgrade)

**Comment by cytopia** [comment]
Yes, use this guide in combination with the one I sent you, to get your data into the Devilbox.

> (still many steps to do manually ... I would still prefer a (semi-)automatic way to upgrade)

Complain at moodle ;p
