### ISSUE TITLE
update composer version

### ISSUE THREAD

**Issue by masiorama** [cytopia/devilbox#218]
Hello, thank you very much for your work.
Is it possible to update the composer version? At the moment the package includes version 1.5.1, while the latest versione is version 1.6.3.

I'm experiencing a few errors and this update should fix them.
Thanks in advance.

**Comment by cytopia** [comment]
@masiorama 
Yes, this problem is being solved in the next release. Each PHP image will always have the latest versions for all tools as they are being built every night.

If you can't wait for the next release to be merged, you can already use it from the open PR:
https://github.com/cytopia/devilbox/pull/203

**Comment by cytopia** [comment]
New release is out and composer is updated:

```bash
devilbox@php-7.2.4 in /shared/httpd $ composer --version
Composer version 1.6.3 2018-01-31 16:28:17
```
