### ISSUE TITLE
sendmail unsupport -X option in cytopia/php-fpm-5.6:0.8.1

### ISSUE THREAD

**Issue by hxer** [cytopia/devilbox#27]
pull `cytopia/php-fpm-5.6:0.8.1`,  write test.php as follow:

```php
<?php
    mail('loc@cc.com', 'test', '<?php phpinfo();?>', null, '-floc@tt.com -OQueueDirectory=/tmp -X/shared/httpd/test/htdocs/rce.php');
    echo 'test mail';
?>
```

then run `php test.php`,  error as follow:

`sendmail: fatal: unsupported: -X/`

maybe reinstall senadmail?

run `yum install sendmail`, it solved.

some information as follow:

* OSX version: 10.12.2
* docker version:1.12.3
* docker-compose version:1.8.1

**Comment by cytopia** [comment]
All PHP dockers have postfix installed.
Can you tell me what the `-X` option is for?

**Comment by cebe** [comment]
X is simply not implemented in the sendmail binary that is provided by postfix. What do you need it for? In case you were trying the PHPMailer/SwiftMailer RCE vulnerability, as far as I see postfix installations are not affected because the do not provide the necessary command line options.

Your "fix" with installing sendmail introduces a conflict as you now have two MTAs installed, not a good idea.

**Comment by cytopia** [comment]
@cebe thanks for the explanation.

@hxer what exactly are you using it for?

**Comment by hxer** [comment]
as @cebe says, in this case, I was trying the PHPMailer RCE vulnerability.

**Comment by cytopia** [comment]
If you can come up with a way to have both, postfix and sendmail installed in parallel, I can make it a startup option within the `.env` file. If both cannot be installed in parallel, I am afraid I cant help it and you will have to manually re-install sendmail on the respective php docker.

I will close this issue, as it cannot be fixed (because I am using postfix for all php dockers).
If you get it to work somehow to have them both installed at the same time, please re-open and let me know how. I will then integrate it.

**Comment by cebe** [comment]
Unless there is a very good reason and very careful configuration, having two MTAs on one machine can cause a lot of trouble so I would vote against doing that.
