### ISSUE TITLE
Make any service optional - select which container to start 

### ISSUE THREAD

**Issue by GiorgosK** [cytopia/devilbox#31]
if you comment out postgressql in .env file I was expecting no postgressql to be loaded but the LATEST is instead loaded ... it would be nice if there was a switch to disable any service from the .env file

**Comment by cytopia** [comment]
Something I am still trying to find a solution for.
The `docker-compose.yml` file does not have conditions and i still don't know a good way for how to get this working. This would obviously the ultimate goal ;-)

**Comment by cytopia** [comment]
@GiorgosK 

Selectively loading docker containers is not possible due to the limitations of docker-compose.
I have however separated the container loading into two types:

1. Base stack (httpd, php, mysql and postgresql)
2. Optional stack (all of the above and redis (others coming soon).

This will be enabled by PR #44

**Comment by cytopia** [comment]
@GiorgosK @jpuck

I finally found a way to make it optional.

Instead of having to define multiple `docker-compose.xxx.yml` files, there will be only one `docker-compose.yml` and you can choose during startup via the following examples:

```shell
# Load all
$ docker-compose up

# Load only httpd and php
$ docker-compose up httpd php

# Load httpd, php, mysql and redis
$ docker-compose up httpd php mysql redis
```

However, for this to work, there is going to be some rewrite necessary. Hope I can get this merged soon.

**Comment by cytopia** [comment]
@GiorgosK Now fixed in new release

**Comment by keithy** [comment]
I added an example of a workaround which shows how to disable a service.
```
version: '2.1'
services: 
  pgsql: #example that disables a service
    image: alpine
    entrypoint: []
```

**Comment by cytopia** [comment]
@keithy there's no need to comment out a specific service as you can simply specify in the startup-command which of the services you want to spin up.

```
docker-compose up httpd php bind mysql
```

See here for more information: https://devilbox.readthedocs.io/en/latest/getting-started/start-the-devilbox.html#start-some-container

**Comment by keithy** [comment]
Understood, just offering an alternative.
