### ISSUE TITLE
setting NEW_UID / NEW_GID don't work

### ISSUE THREAD

**Issue by srattay** [cytopia/devilbox#317]
#### ISSUE TYPE

 - Question

#### SUMMARY

Here on my OSX host my uid=501 and my gid=20
So i set NEW_ID=501 and NEW_GID=20 in .env
Starting with `docker-compose up` throws following error:
`httpd_1  | [WARN] Group with 20 already exists: dialout`

What can i do to get it work?

**Comment by cytopia** [comment]
@srattay 
This is just a warning, not an error. Is anything not working?

**Comment by cytopia** [comment]
@srattay 
As this is a bug, rather than a question, please provide all information as defined here: https://github.com/cytopia/devilbox/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

* also attach `.env` file
* Do you have any custom vhost-gen templates in place
* list contents of `data/www` (to check the project names)

**Comment by cytopia** [comment]
Closing in favour of: https://github.com/cytopia/devilbox/issues/318

**Comment by srattay** [comment]
@cytopia 
thanks for your advice
i opened a bugreport
does it make sense to use a previous version?
