### ISSUE TITLE
adding subdomain for apache 2.4

### ISSUE THREAD

**Issue by uabassguy** [cytopia/devilbox#362]
#### ISSUE TYPE

 - Documentation

#### SUMMARY

According to the docs here https://devilbox.readthedocs.io/en/latest/vhost-gen/example-add-subdomains.html?highlight=vhost#tutorial-adding-sub-domains-apply-changes
It says the instructions are the same for apache 2.4
But, when starting we get this error:
httpd_1  | AH00526: Syntax error on line 3 of /etc/httpd/vhost.d/my-project.conf:
httpd_1  | Invalid ServerName "*.my-project.loc" use ServerAlias to set multiple server names.
httpd_1  | 2018-08-21 11:46:37,059 INFO exited: httpd (exit status 1; not expected)

So, if we change the yml on line 4 (the 2nd ServerName) to:

ServerAlias *.__VHOST_NAME__

The error goes away on next docker-compose up, and the subdomains will work now.

#### Goal

Slight correction to add ServerAlias directive in apache 2.4
Reference: https://httpd.apache.org/docs/2.4/mod/core.html#serveralias

**Comment by cytopia** [comment]
Good catch.

**Comment by cytopia** [comment]
@uabassguy 

So multiple `ServerName` directives are invalid for Apache 2.4.  Aren't they also invalid for Apache 2.2?

**Comment by masiorama** [comment]
Sorry to comment on this old issue, but I'm scratching my head since yesterday and I cannot solve my problem so far.
I read all devilbox docs about the matter, but I cannot find a way to successfully add 2 vhosts inside a single codebase, like it is supposed to do with a yii2-app-advanced: https://www.yiiframework.com/extension/yiisoft/yii2-app-advanced/doc/guide/2.0/en/start-installation#preparing-application

As you can see inside the link (the 2 apache vhosts), the project root is the same `/path/to/yii-application/` but 2 app (folders `frontend` and `backend`) and therefore 2 webroots should be accessible... is this possibile with devilbox as it is now?
