### ISSUE TITLE
[Win10] Updating from 18.06.0-ce to 18.06.1-ce crashes all set of containers

### ISSUE THREAD

**Issue by gpimentelv** [cytopia/devilbox#374]
#### ISSUE TYPE

 - Bug Report

#### OS / ENVIRONMENT

1. Host operating system: Windows 10 1803 Update August 2018
2. Native Docker or Docker Toolbox: Native Docker
3. Docker version: 18.06.1
4. Docker Compose version: 1.22
5. What containers are running: httpd php mysql redis
6. Container versions: 
- cytopia/mariadb-10.1:latest
- redis:4.0
- devilbox/nginx-stable:0.22
- devilbox/php-fpm:7.2-work-0.37
- cytopia/bind:0.15

#### SUMMARY

Just two weeks ago started to get close and personal with Docker, and i came across this magnificent stack called DevilBox.
So, i installed Docker **18.06.0-ce** (on Windows 10, too soon to make the jump to GNU/Linux), read the docs, and set my first containers online, it was amazin how easy everything worked on just 10 minutes! no more XAMPP, AMPPS.

Tried some WP/CodeIgniter to warm up, just fine.

The next day, at Windows startup, docker tells me an update **18.06.1-ce** is coming, so i did.
After that, everything on docker-compose (For DevilBox) seems to be running normal but failed to connect.

I tried other containers (Nagios) and they worked fine

That's it, 3 days of pondering, nerve-wrecking scenarios to came to th conclusion:

Hey, why don't just rollback to the previous version?

[SOLVED] Just reporting

#### STEPS TO REPRODUCE

From 18.06.0-ce on Windows 10:
- Cloned the Latest GIT, make the basic changes on .env (Timezone, Intranet Password)
- docker-compose up -d httpd php mysql redis // docker-compose up -d httpd php pgsql redis
- All Fine and Dandy!! MySQL/pgSQL ok, composer ok, laravel/cakephp/ci ok, prestashop/wp/joomla ok
- Stop containers and exit docker
#### BUT THEN
- Open Docker, update notice shows
- Update Docker to 18.06.1-ce
- Repeat → docker-compose up -d httpd php mysql redis
- Nothing seems to work

#### EXPECTED BEHAVIOUR

- Same behaviour as 18.06.0-ce

#### ACTUAL BEHAVIOUR

- Cannot acces Intranet, or connect to MySQL/pgSQL

#### OTHER INFORMATION

- Dude, im a rookie so no custom moves

**Comment by cytopia** [comment]
@gpimentelv thanks for reporting this. I leave this open for visibility.

**Comment by JakubHelis** [comment]
@cytopia 
I guess same on the Linux Manjaro - docker 18.06.1-ce, the httpd container throwing error ( checked apache and nginx ) - Just a guess, because i didn't change anything, but only standard updates (yay -Suy ;) ) 

`ttpd_1  | [INFO] vhost-gen: no customized template found
httpd_1  | vhostgen: [2018-09-13 08:54:24] Adding: localhost
httpd_1  | $ openssl req -newkey rsa:2048 -nodes -extensions v3_req -keyout /etc/httpd/cert/main/localhost.key -subj '/C=DE/ST=Berlin/L=Berlin/O=Devilbox/OU=Devilbox/CN=localhost/emailAddress=admin@localhost' -out /etc/httpd/cert/main/localhost.csr
httpd_1  | $ openssl x509 -req -extensions v3_req -extfile <(printf '[ req ]\nreq_extensions = v3_req\n[ v3_req ]\nsubjectAltName=DNS.1:localhost,DNS.2:localhost,DNS.2:*.localhost,DNS.2:devilbox,DNS.2:*.devilbox\n') -days 3650 -in /etc/httpd/cert/main/localhost.csr -CA /ca/devilbox-ca.crt -CAkey /ca/devilbox-ca.key -CAcreateserial -out /etc/httpd/cert/main/localhost.crt
httpd_1  | Signature ok
httpd_1  | subject=/C=DE/ST=Berlin/L=Berlin/O=Devilbox/OU=Devilbox/CN=localhost/emailAddress=admin@localhost
httpd_1  | Getting CA Private Key
httpd_1  | unable to load number from /ca/devilbox-ca.srl
httpd_1  | 140401747617424:error:06067099:digital envelope routines:EVP_PKEY_copy_parameters:different parameters:p_lib.c:137:
httpd_1  | 140401747617424:error:0D066096:asn1 encoding routines:a2i_ASN1_INTEGER:short line:f_int.c:210:
`

**Comment by alzen8work** [comment]
![image](https://user-images.githubusercontent.com/20431509/46452060-5352ef00-c7cc-11e8-8946-47210a8b4265.png)

**Comment by alzen8work** [comment]
so what may be the action plan? revert to old docker?

**Comment by cytopia** [comment]
@alzen8work are you using this version? If so, then revert to a previous minor version

**Comment by alzen8work** [comment]
![image](https://user-images.githubusercontent.com/20431509/46549343-3faaa400-c904-11e8-9230-ff86a6ab6a6b.png)

**Comment by alzen8work** [comment]
> @alzen8work are you using this version? If so, then revert to a previous minor version

i have downgrade to Docker 18.03.1-ce win65

**Comment by alzen8work** [comment]
https://docs.docker.com/docker-for-windows/release-notes/

the ones i tried:
Docker Community Edition 18.03.1-ce-win65 2018-04-30
Docker Community Edition 18.06.0-ce-win70 2018-07-25
Docker Community Edition 18.06.0-ce-win72 2018-07-26
Docker Community Edition 18.06.1-ce-win73 2018-08-29

all so far is not working

**Comment by cytopia** [comment]
@alzen8work what is the name of your Devilbox directory? Does it start with underscores? If so, it must start with `[a-zA-Z0-9]`.

**Comment by alzen8work** [comment]
the name is __dvbx_20181001 

i've change it to dvbx_20181001, and it seems is working already

**Comment by alzen8work** [comment]
ive use the branch called docker-volume not sure whether it is the correct branch to play ard though

**Comment by cytopia** [comment]
> [SOLVED] Just reporting

@gpimentelv, OK I will close this one then.

---

> ive use the branch called docker-volume not sure whether it is the correct branch to play ard though

@alzen8work, You should go on that branch here from now on: https://github.com/cytopia/devilbox/pull/416

**Comment by vikas5914** [comment]
[appveyor](https://www.appveyor.com/) has windows Ci. no idea about the docker
