### ISSUE TITLE
How to use alpine images

### ISSUE THREAD

**Issue by hetykai** [cytopia/devilbox#429]
#### ISSUE TYPE

 - Feature request

#### SUMMARY
The images are so big, I just want use alpine image.

#### Goal
All the images are so big, how can i use alpine images?
I found that modifying the .env file can change some of the image, like this:
```
PGSQL_SERVER=alpine
REDIS_SERVER=alpine
MEMCD_SERVER=alpine
```

But how to change other images to alpine? The php and mysql images are too big.

**Comment by cytopia** [comment]
All images except PHP, HTTPD, BIND and MYSQL could be easily switched to Alpine with some minor work on configuration that I would have to submit.

* For Bind I am currently working on a complete rewrite based on Alpine
* MySQL needs some more work to base MySQL, MariaDB and PerconaDB on offical images and then also go full Alpine with it
* HTTPD (Apache/Nginx) would also require some more work

However for PHP it is kinda difficult. I initially had both, Alpine and Debian. However the Alpine versions were limited as not all modules compiled on it due to lack of libc. I think the final PHP images would also not be as small as assumed, as they provide a lot of tools which will eat up space anyway.

**Comment by cytopia** [comment]
@hetykai PR is on the way: https://github.com/cytopia/devilbox/pull/443

Not all images can be replaced with Alpine versions as not everybody is providing them yet.
