### ISSUE TITLE
Change default php.ini entry - memory_limit

### ISSUE THREAD

**Issue by fkaminski** [cytopia/devilbox#469]
#### ISSUE TYPE

 - Feature request

#### SUMMARY

By default the PHP memory_limit is set to 512M.

As nowadays more and more web apps are installed via PHP Composer I would suggest to set this to:
memory_limit = -1
as default for PHP Cli and Frontend ...

#### Goal

It does not hurt - and prevent us to do this manually for every PHP version ...

**Comment by cytopia** [comment]
I am currently exploring the idea to separate php-cli ini configurations and php-fpm ini configuration.

This would allow to have separate settings for cli, such as having `xdebug` disabled, and increased memory limits without affecting the sites itself.

It will also resolve the issue using `composer` on the cli when `xdebug` is enabled.

**Comment by fkaminski** [comment]
Sounds good for me,
but why not set memory_limit=-1 as default entry in general?
I have no problems using composer with devilbox except the memory limit issue:
https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors

**Comment by cytopia** [comment]
> but why not set memory_limit=-1 as default entry in general?

I agree for the cli application to have it set to `-1`, but for php-fpm i am thinking that it should have a sane and limited default. Your production server will most likely not use `-1` either, and I generally make sure to use similar values in order to catch shortcomings already during development and not just after release. But I am also fine with learning more about other people's use cases and adopt accordingly.

Also try to bare in mind, that I want to keep the default settings as general as possible in order to please most of the users.


> I have no problems using composer with devilbox except the memory limit issue:

To give you a quick solution to your current issue, have a look at how to set it to `-1` for both, the cli and php-fpm: https://devilbox.readthedocs.io/en/latest/configuration-files/php-ini.html

Let me know if this satisfy your use case for now. Splitting configs for cli and fpm will require a bit of time from my side.

**Comment by fkaminski** [comment]
Yes, I can override/set this php.ini value manually in the cfg folder - just too lazy - therefore this issue ...
But I understand your concern in this regard and will close ist for now.
Thanks

**Comment by cytopia** [comment]
OK, thanks for the understanding. I will announce once the php-cli and php-fpm ini separation is out.
