### ISSUE TITLE
Add cli commands

### ISSUE THREAD

**Issue by louisgab** [cytopia/devilbox#527]
#### ISSUE TYPE
 - Feature request

#### SUMMARY
I often need to change the `.env` file, mainly because I switch between professional and personal projects which have their own separate folders and configurations.
I had an idea of a cli tool and wanted to share it with you in case it was helpful:
https://github.com/louisgab/devilbox-cli
Its very basic but we can later implement a `devilbox update` command for example.

#### Goal
Simplify and accelerate the time needed to change a config in `.env` file.

**Comment by cytopia** [comment]
Thanks for the great work, this is going to be useful for many people :+1: 

One thing however I would question is the hard-coded path of the Devilbox: https://github.com/louisgab/devilbox-cli/blob/master/devilbox-cli.sh#L7

---

As I currently do not have the capactiy to jump into that and my plans for a cli haven't reached a
very thoughtful state yet, I will leave it for now as a third-party tool and close this issue.


It's been added to the documentation: https://devilbox.readthedocs.io/en/latest/third-party/devilbox-cli.html

Feel free to enhance/extend this section to make it easy for people to use and get more feedback by having more users.


Also to get more visibility on this, I would suggest to put this into the Forums rather than having it a GitHub issues as it is now an external tool: https://devilbox.discourse.group

Thanks again for the work!

**Comment by louisgab** [comment]
Thanks for your interest and feedback!
You're right, it was quick and easy like that for my usage (I move data outside devilbox like mentioned in your best practices) but I will try to avoid the hardcoded path to match other people needs, in the future releases.
