### ISSUE TITLE
Issues accessing Devilbox Intranet

### ISSUE THREAD

**Issue by zaewin** [cytopia/devilbox#585]
Did a clean install of Ubuntu and downloaded The Devilbox. Everything seems to work and I can access my local projects with virtual hosts. However, I can't access the Devilbox intranet through localhost or 127.0.0.1

Any idea why this happens?

**Comment by rodolfoberrios** [comment]
In Linux you have to use `172.16.238.11` instead of `127.0.0.1` for httpd. The problem is that this whole thing is built with the notion of localhost resolver, for example: In the vhost section the system tells you to create host entries for `127.0.0.1` which won't work and devilbox will complain about these not being present in your `/etc/hosts` file.

Same goes to every possible host that Docker-Compose may declare, for example, host `mysql` won't work, but `172.16.238.12` will do.

https://devilbox.readthedocs.io/en/latest/advanced/connect-to-host-os.html#docker-on-linux

**Comment by zaewin** [comment]
Aha, I see! The funny thing, however, is that I'm getting the same result for localhost, 127.0.0.1 and 172.16.238.11 which is "404 Not found (nginx/1.14.2)". localhost used to work before I installed the latest version.

**Comment by cytopia** [comment]
@zaewin it should definitely be available on `127.0.0.1` or `localhost`, especially on Linux. Please try to normalize your `.env` file with `env-example`, checkout latest stable git tag and if this does not work, you should open a detailed bug report with steps to reproduce.
