### ISSUE TITLE
Please add phpmd

### ISSUE THREAD

**Issue by insyht** [cytopia/devilbox#615]
#### ISSUE TYPE
 - Feature request

#### SUMMARY
Please add PHP Mess Detector to Devilbox, just like for example PHPCS has been added.

#### Goal
I want to be able to use PHPMD in the PHP container.

More information about PHPMD: https://phpmd.org/

**Comment by llaville** [comment]
Hello All,
I've reacted with thumbs down, because I don't think we should add QA tools in PHP container.
If we want to have this tool (`phpmd`) and others, I suggest to have a look on project https://github.com/jakzal/phpqa
I used it since few days, and I like it : there are many QA tools available.

**Comment by insyht** [comment]
There are already a few PHP QA tools in the container, like phpcs 😉

**Comment by insyht** [comment]
So what do you guys think? Can you add PHPMD to the container, alongside the already available tools like phpcs?
