### ISSUE TITLE
Devilbox Root CA not trusted on macOS Mojave 10.14.16

### ISSUE THREAD

**Issue by ops-andy** [cytopia/devilbox#631]
### ISSUE TYPE

 - Documentation

### OS / ENVIRONMENT

1. Host operating system and version: macOS Mojave 10.14.16
2. (Windows) Native Docker or Docker Toolbox: Docker on Mac
3. Docker version: 19.03.2
4. Docker Compose version: 1.24.1
5. (Linux) Is SELinux enabled?: n/a
6. What git commit hash are you on?: 0543f2da9218661824c64148e07f601f5e99f302

I've added the devilbox-ca.crt to my keychain under both login-> Certifcates and system-> Certificates. 
In the keychain pane I get a message that says "Devilbox Root CA" certificate is not trusted. When I try to load any of my sites in Chrome with https:// I get the message that the site is unsecure and reverts to non-https.

I haven't seen any one else having this issue, am I missing something?

**Comment by ops-andy** [comment]
I found that even after I added the to my keychain, I then had to right click on the CA -> Get Info -> Trust -> Always Trust. Once I set that, everything is as expected.
probably change this to documentation rather than bug.

**Comment by guptaru1** [comment]
Good day,
I am running a Catalina server on my MacBook and I have Devilbox and docker set up on my laptop and I am getting a 502 bad gateway error saying that it is exiting out out of PHP 7.2 container with a "cant write into var/log/php permission denied" and I am assuming that because the PHP 7.2 container is exiting out I am getting a 502 bad gateway error

**Comment by science695** [comment]
Hey @guptaru1, I would recommend starting your own issue, and including the config / log files that it mentions.
