### ISSUE TITLE
How to add ffmpeg and run it from shell

### ISSUE THREAD

**Issue by folkevil** [cytopia/devilbox#639]
#### ISSUE TYPE

 - Question

#### SUMMARY
I'm trying to add ffmpeg to devilbox, and run it from inside shell, tried to add custom container () via  docker-compose.override but no luck.

 Any help please ?

**Comment by mrbig00** [comment]
You can ssh in the container and install it yourself:

```
apt-get update && apt-get install ghostscript
```

or you can add to the rebuild script and every time it will install when the images are updated:
```
docker-compose exec php 'apt-get update && apt-get install ghostscript'
```

**Comment by folkevil** [comment]
@mrbig00 thanks, I forgot to add sudo =.='

But how about to link existing ffmpeg docker image to PHP container? Any suggestion please?

**Comment by mrbig00** [comment]
that command does not creates a separate container, it installs ffmpeg in the php container

**Comment by cytopia** [comment]
@folkevil hope that solves your question.
I was looking into adding this to the PHP container by default, but it just pulls into way too much overhead and will increase the image size quite a lot.

You can however just install it during runtime and use it from there.

Manual installation will also survive Docker Compose restarts (if you do not `docker-compose rm`).
So next time you start up Devilbox again, it will still be available.

**Comment by KrunalRajkotiya** [comment]
hey @cytopia,
I have been facing similar kind of issue with **ffmpeg**.
 I am using the **ffmpeg** for converting my **mp4** files into **wav** format using **subprocess**.
I have added the **ffmpeg** in the _requirements.txt_ but at the time of excution of code locally on cloud shell it's showing me error like _ffmpeg not found_.
So I was trying to deploy my code in the **GCP  APP Engine** with some files like **_main.py_**, **_app.yaml_**  and **_requirements.txt_** .
But in the app deployment it's throwing the warning _**ffmpeg** not found on runtime_ so can you suggest how I can install **ffmpeg** so that my code get  deploy and works perfectly fine. 
I have searched about it and all the place I see **Docker** as best suggestion if it so then what will be there in my **Docker** file?
