### ISSUE TITLE
Configure grunt-contrib-watch with livereload option for Devilbox

### ISSUE THREAD

**Issue by robots4life** [cytopia/devilbox#652]
I would love to be able to use https://github.com/gruntjs/grunt-contrib-watch with the livereload option https://github.com/gruntjs/grunt-contrib-watch#optionslivereload alongside Devilbox and VS Code.

```
npm install grunt-contrib-watch --save-dev
```
In the `Gruntfile.js`, among other things, I have this.
```
watch: {
    scss: {
    files: [
        '/shared/httpd/projectabc/htdocs/scss/style_scss.scss'
    ],
    options: {
        livereload: true,
        // livereload: 1337,
        keepAlive: true
    },
    tasks: ['sass', 'postcss', 'cssmin']
},
```
The Gruntfile works fine inside Devilbox, I can compile scss to css, minify, uglify, etc.

Now when I run the watch task **outside** the Devilbox a live reload server will be started with the watch task per target. When I include [the livereload script](https://github.com/gruntjs/grunt-contrib-watch/blob/master/docs/watch-examples.md#enabling-live-reload-in-your-html) in the HTML it works fine for the site and page I am working on.

This works because the livereload script will be hosted at `localhost:35729/livereload.js` once the watch task is running.

However I would not know how to do this inside Devilbox. I cannot figure out where the watch task hosts the livereload script inside Devilbox. I tried different ports as well as setting the URL of the site I work on to the URL of the livereload script as well.

`http://projectabc.loc:35729/livereload.js` or `https://projectabc.loc:35729/livereload.js` or `http://projectabc.loc:1337/livereload.js` but when I check that URL it just gives me a 404.

Outside Devilbox I can see the livereload script just fine under the `localhost:35729/livereload.js` URL.

Is there a way to do this at all inside Devilbox? How would I be able to see where the watch task spins up the server and then "connect it" or make it "pass through" to Devilbox?

So far I have not tried using the web extensions [1](https://addons.mozilla.org/en-US/firefox/addon/livereload-web-extension/), [2](https://addons.mozilla.org/en-US/firefox/addon/live-reload/) or what is recommended [here](http://livereload.com/extensions/) or links to [here](https://github.com/guard/guard-livereload) from the main livereload.com site under "Linux?".

@boumanb do you maybe have an idea? ;) If not what are you using to get livereload working in your projects?

**Comment by boumanb** [comment]
Hi,

Thanks for the extensive write-up. Because of it I managed to do some testing, I'm not that familiar with Grunt etc. However, the good news is: I've managed to get it working! :smile: 

Because you're visiting the project through the browser on the host it's not able to resolve `<script src="//localhost:35729/livereload.js"></script>` (because it is being hosted inside the `php` container). We need to tell docker to expose that particular port `35729` so that we can reach the `livereload.js` inside of the `php` container from our host system.

This is done like this:

1. Navigate to the Devilbox root directory (where `.env` and `docker-compose.yml` are located) and create a new file (if you don't have one already) called `docker-compose.override.yml`.
2.  Copy the following into the file:
```
# IMPORTANT: The version must match the version of docker-compose.yml
version: '2.1'

services:
  php:
    ports:
      # ---- Format: ----
      # [HOST-ADDR : ] HOST-PORT : DOCKER-PORT
      - "35729:35729"
```
3. Now restart Devilbox and make sure the following is in the `<head>` of your project: `<script src="//localhost:35729/livereload.js"></script>` 
4. Run `grunt watch` inside Devilbox
5. Make a change and if all is fine it should now livereload

**Comment by robots4life** [comment]
Dear @boumanb 
I can't thank you enough for helping me out on this one. Thank you! :hugs: 
Saw this yesterday and it was like a Christmas present, quite neat. :heart: 

Seeing how this works I can observe a pattern here, we are mainly doing work in the php container and any services that I might want/need would have to be connected from the host to the container. Well, if they are not already supplied with Devilbox. :wink: 

p.s. went on to check your personal website but the certificate expired, get that sorted and all the best in your coding adventures. :+1:

**Comment by boumanb** [comment]
> Seeing how this works I can observe a pattern here, we are mainly doing work in the php container and any services that I might want/need would have to be connected from the host to the container. Well, if they are not already supplied with Devilbox. 😉

Exactly. 😄 

> p.s. went on to check your personal website but the certificate expired, get that sorted and all the best in your coding adventures. 👍

Thanks for notifying me. I forgot I had it. 

You can resolve this issue if everything is working as supposed, thanks!
