### ISSUE TITLE
Setting MYSQL_ROOT_PASSWORD NOT WORKING

### ISSUE THREAD

**Issue by lnsane** [cytopia/devilbox#699]
################################################################################
###
###
################################################################################

###
###
###
###
###
MYSQL_ROOT_PASSWORD='123456'

I try MYSQL_ROOT_PASSWORD='123456' or MYSQL_ROOT_PASSWORD=123456 or MYSQL_ROOT_PASSWORD="123456"

but MYSQL_ROOT_PASSWORD is default value empty

why?

**Comment by cytopia** [comment]
@lnsane when submitting bug reports, please use/fill out correctly the GitHub issue template for bugs and specify/describe all the steps to reproduce this, otherwise it won't be possible to triage your bug.

Generally speaking, the MySQL root password change does work as shown here by the CI jobs: https://github.com/cytopia/devilbox/runs/532864471?check_suite_focus=true#step:6:49

**Comment by lnsane** [comment]
...
