### ISSUE TITLE
PostgreSQL timezone settings

### ISSUE THREAD

**Issue by ilsenem** [cytopia/devilbox#76]
- Ubuntu 16.04
- Docker 17.03.1-ce
- docker-compose 1.13.0

I don't know if this is by design or a missed feature, but when i set configuration value for TIMEZONE, it propagates everywhere except (what i notice) PostgreSQL settings. My timezone is `Asia/Novosibirsk` but `postgres` show me that my timezone is `UTC`.

**Comment by cytopia** [comment]
@ilsenem The problem here is that the devilbox is using official postgresql docker and they do not offer to change the timezone. This is not something I can change. Only way around this, is to create custom postgresql docker container.

Let me know if this is a crucial feature, then I can put it on the Roadmap: #23 .

**Comment by ilsenem** [comment]
Since `Devilbox` suppose to work on developer machine only, this is not a crucial feature at all. It was expected behaviour but not required. Thanks for answer.
