### ISSUE TITLE
New php extensions

### ISSUE THREAD

**Issue by bogdaniel** [cytopia/devilbox#792]
I've started using devilbox to work on symfony projects because I find it easy since it comes with blackfire implemented but today when I tried to install a simple packages ( twig-ext ) I noticed I don't have the ext-http extension. Took me around 4 hours to figure it out how to install the package.
Would be great if we would have by default installed the following extensions : http.so, propro.so raphf.so.

Thank you.

**Comment by llaville** [comment]
Hello @bogdaniel 

As Cytopia seems to be very busy, I'll try to explain how you can  add your own extension easily !

Probably a new chapter in awesome documentation will be greatly appreciated by the community. 

By default, the Devilbox used php container (Docker image mods https://github.com/devilbox/docker-php-fpm#image-mods) to enable/disable php modules (extensions).
If you want to build your own php images, have a look on the [build helper](https://github.com/devilbox/docker-php-fpm/tree/0.123/build) and especially on [build/ansible/group_vars/all/mods.yml](https://github.com/devilbox/docker-php-fpm/blob/0.123/build/ansible/group_vars/all/mods.yml#L14)
As you can see, the php modules you hope to see are not defined in list, but you can add it and rebuild docker images locally.
Uses the `Makefile` of the project.
Then once each php images (base, mods, prod, work) will be generated, follow official documentation to know how to [overwrite existing docker image](https://devilbox.readthedocs.io/en/latest/advanced/overwrite-existing-docker-image.html).

As current project cannot be built since a long time now (https://github.com/devilbox/docker-php-fpm/issues/195), I suggest to read also my proposition and fork version (https://github.com/devilbox/docker-php-fpm/issues/199) to build your own versions.

Hope this introduction will help you !

**Comment by llaville** [comment]
Notice, for [http extension](https://pecl.php.net/package/pecl_http) you need: 

- for PHP 8, version 4.0.0 or greater + **raphf** ext (**propro* no more required)
- for PHP 7, version 3.2.4 + **raphf** and **propro** ext

That means, you must also configure extension definition in `build/ansible/group_vars/all/mods.yml` file.
Something like (this patch)

```
diff --git a/build/ansible/group_vars/all/mods.yml b/build/ansible/group_vars/all/mods.yml
index 934482c..f7d182c 100644
--- a/build/ansible/group_vars/all/mods.yml
+++ b/build/ansible/group_vars/all/mods.yml
@@ -658,6 +658,19 @@ extensions_available:
       type: pecl
       build_dep: [unixodbc-dev]
       run_dep: [unixodbc]
+  pecl_http:
+    disabled: [8.1]
+    7.2:
+      type: pecl
+      version: 3.2.4
+    7.3:
+      type: pecl
+      version: 3.2.4
+    7.4:
+      type: pecl
+      version: 3.2.4
+    all:
+      type: pecl
   pgsql:
     all:
       type: builtin
@@ -720,11 +733,19 @@ extensions_available:
       build_dep: [libssl-dev]
   posix:
     already_avail: "{{ php_all_versions }}"
+  propro:
+    disabled: [8.0, 8.1]
+    all:
+      type: pecl
   pspell:
     all:
       type: builtin
       build_dep: [libpspell-dev]
       run_dep: [libaspell15]
+  raphf:
+    disabled: []
+    all:
+      type: pecl
   readline:
     already_avail: "{{ php_all_versions }}"
   recode:
```

**Comment by llaville** [comment]
As **pecl_http** extension requires [some dependencies](https://mdref.m6w6.name/http#Dependencies:), the previous patch should be upgrade to:

```
diff --git a/build/ansible/group_vars/all/mods.yml b/build/ansible/group_vars/all/mods.yml
index 934482c..d87a1d0 100644
--- a/build/ansible/group_vars/all/mods.yml
+++ b/build/ansible/group_vars/all/mods.yml
@@ -658,6 +658,28 @@ extensions_available:
       type: pecl
       build_dep: [unixodbc-dev]
       run_dep: [unixodbc]
+  pecl_http:
+    disabled: [8.1]
+    7.2:
+      type: pecl
+      version: 3.2.4
+    7.3:
+      type: pecl
+      version: 3.2.4
+    7.4:
+      type: pecl
+      version: 3.2.4
+    all:
+      type: pecl
+      build_dep:
+        - zlib1g-dev
+      run_dep:
+        - libcurl4-openssl-dev
+        - libbrotli-dev
+        - libevent-dev
+        - libicu-dev
+        - libidn11-dev
+        - libidn2-0-dev
   pgsql:
     all:
       type: builtin
@@ -720,11 +742,19 @@ extensions_available:
       build_dep: [libssl-dev]
   posix:
     already_avail: "{{ php_all_versions }}"
+  propro:
+    disabled: [8.0, 8.1]
+    all:
+      type: pecl
   pspell:
     all:
       type: builtin
       build_dep: [libpspell-dev]
       run_dep: [libaspell15]
+  raphf:
+    disabled: []
+    all:
+      type: pecl
   readline:
     already_avail: "{{ php_all_versions }}"
   recode:
```

**WARNING** I'm working to include it in my fork version: should be available soon ...

**Comment by llaville** [comment]
FYI: my fork is ready to enable http extension on platforms PHP 7.2, 7.3, 7.4 and 8.0

**Comment by bogdaniel** [comment]
Thank you everyone for the answers solved the issues somehow based on some docs I found to load from mods folder and cfg folder, but I will read every comment and do it your way. Also thank you for the fork :D
