### ISSUE TITLE
Does Devilbox work on Apple Silicon?

### ISSUE THREAD

**Issue by frumbert** [cytopia/devilbox#822]
there a way to install or run Devilbox on Apple M1 Macs?

Attached is a log of performing `docker-compose up` on a new installation. Look like dystopia/bind, devilbox/php-fpm, devilbox/apache and devilbox/mysql all use amd64 images. How does one switch to arm64 images?

[docker-compose up M1.txt](https://github.com/cytopia/devilbox/files/6746681/docker-compose.up.M1.txt)

**Comment by cytopia** [comment]
> there a way to install or run Devilbox on Apple M1 Macs?

There are no arm64 images available at the moment.

**Comment by Lenitr** [comment]
I'm wondering if you're thinking of supporting arm64 in the future? Or are you dependant on others to test this?

Thanks a lot for your effort and time in this project!

**Comment by mhodge13** [comment]
This article may help when you are ready to create the arm64 images.

https://www.docker.com/blog/multi-arch-images/

**Comment by boumanb** [comment]
Got Devilbox to run on my MacBook Air (MBA) M1 (16GB/512GB) (which I received last week, returning it) without any modifications. Executing `docker-compose up` is all you need to do right now.

However; the performance is horrible. This has nothing to do with Devilbox. 

It's the IO operations on mounted volumes on Mac devices. Performance was okay on my 2020 MacBook Pro, nothing compared to linux but, okay. One way to tweak performance of the mounted volumes is leveraging NFS as instructed [here](https://www.jeffgeerling.com/blog/2020/revisiting-docker-macs-performance-nfs-volumes). It enhances performance greatly. 

_I'll look into writing a PR to provide documentation (steps and/ or basic files) on how to set this up._

On the MBA M1 I've received I installed docker, cloned devilbox and started testing with and without NFS mounted volumes. The results of running `time composer install --no-cache` inside devilbox below:

Without NFS setup | real | user | sys
-- | -- | -- | --
1 | 1m25.686s | 0m42.663s | 0m13.287s
2 | 1m19.531s | 0m41.323s | 0m13.141s
3 | 1m23.592s | 0m42.235s | 0m13.373s
  |   |   |  
With NFS setup | real | user | sys
1 | 0m43.027s | 0m31.816s | 0m10.757s
2 | 0m45.518s | 0m30.987s | 0m10.458s
3 | 0m41.481s | 0m30.906s | 0m10.508s

With these results (using NFS setup) the performance on the MBA M1 is slightly worse compared to my "old" MacBook Pro 2020 Intel (16GB/512GB). Also, I like to make use of [Remote Development - Containers](https://code.visualstudio.com/docs/remote/containers) in VS Code, it enables me to do everything from within my VS Code window (running commands in the integrated terminal directly in devilbox and editing source files). Also, some extensions require PHP, which I want to keep off my host system, they are able to run because they are being installed inside of the development container by VS Code. It is great.

This forces me to return it, because I was looking for a upgrade in contrast to a downgrade. 

I have to admit, running commands like `npm install` run unbelievably fast on the host, just not inside of devilbox (docker). People are able to workaround the problem by running certain commands on the host machine but that's not the preferred workflow. The M1 is great. It does not get warm, the fans won't turn on (because it doesn't have them :)) and the battery is great (docker does drain it so shut that down when not using it).

**Comment by cytopia** [comment]
I was looking into building ARM images. This however seems to be rather problematic. I have currently tested it with a base image (PHP 8.2) in this PR: https://github.com/devilbox/docker-php-fpm-8.2/pull/2

* **AMD64** image builds in about **9 minutes** (as it did in single run before)
* **ARM64** image builds in about **100 minutes** (more than factor 11 longer)

Timewise it would all be do-able for the used Docker images for Devilbox, however, when looking at the actual PHP images, the fastest pipeline was 1 hours. When doing ARM64 images the pipeline will most likely also be (more than) 11 times slower, which would result into something like at least **11 hours** per build.

As far as I've read, GitHub actions allows a maximum of **6 hours** per job, so that would be currently impossible.

Additionally, as this is only a non-commercial project I'm doing in my spare-time and migrating, testing and fixing tens of docker images would take months and lots of energey, it is something which I'm unable take. I will leave this to the community.

If somebody wants to step in and take action and is also able to solve the long-running pipelines, then let me know and we can work something out.

**Comment by cytopia** [comment]
Closing in favour of this: https://github.com/cytopia/devilbox/issues/855
