### ISSUE TITLE
PHP 8.1 with AVIF Support in GD extension

### ISSUE THREAD

**Issue by robots4life** [cytopia/devilbox#834]
The GD extension in PHP 8.1 and later supports the AVIF image format, making it possible to convert images from and to AVIF.
For this to work the GD extension must be compiled with AVIF support.
It depends on libavif package, which may not be available in default repositories of older operating system versions.

[https://php.watch/versions/8.1/gd-avif#compile](https://php.watch/versions/8.1/gd-avif#compile)

Could you kindly compile PHP 8.1 with AVIF support ?

**Comment by llaville** [comment]
@robots4life Good news. Project `docker-php-extension-installer` since today release [1.2.65](https://github.com/mlocati/docker-php-extension-installer/releases/tag/1.2.65) add support to enable AVIF for GD on PHP 8.1

And I've already mentioned it, my [alternative](https://github.com/llaville/docker-php-toolbox) which is almost compatible to https://github.com/devilbox/docker-php-fpm  (see my current [ROADMAP](https://github.com/llaville/docker-php-toolbox/blob/master/ROADMAP.md) to learn more about compatibility between two solutions) used the `docker-php-extension-installer`project to add extension in `mods` image

**Comment by robots4life** [comment]
@llaville Good work and thank you for the update on this.

For local development this is good, going live, many hosts have not implemented this and imo this will still take a while. For working with JPEG files and converting them to AVIF I can observe a trend where some basic PHP hosts have Node on the console, with this I pass the files to the Node process, convert them there with Sharp and pass them back to the location where PHP can serve them. This works locally and live for the hosts in question.

However, it would also be cool to know if the `docker-php-extension-installer` project can/could be used to enable AVIF for GD on PHP 8.1 in Devilbox.

**Comment by llaville** [comment]
> However, it would also be cool to know if the `docker-php-extension-installer` project can/could be used to enable AVIF for GD on PHP 8.1 in Devilbox.

/cc @cytopia

**Comment by cytopia** [comment]
Added
