### ISSUE TITLE
rsyslogd is not running, but required for mail logging.

### ISSUE THREAD

**Issue by onasipim** [cytopia/devilbox#854]
Devilbox logs constantly during running:
`php_1    | rsyslogd is not running, but required for mail logging.
php_1    | 2021-12-16 23:36:24,576 INFO exited: postfix (exit status 1; not expected)
php_1    | 2021-12-16 23:36:25,652 INFO spawned: 'postfix' with pid 5433
php_1    | 2021-12-16 23:36:26,676 INFO success: postfix entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
`

During startup I get:
`php_1    | rsyslogd: pthread_getschedparam failed during startup - ignoring. Error was Operation not permitted
php_1    | rsyslogd: imklog: cannot open kernel log (/proc/kmsg): Operation not permitted.
php_1    | rsyslogd: activation of module imklog failed [v8.1901.0 try https://www.rsyslog.com/e/2145 ]`

Starting Devilbox with:
`docker-compose up bind httpd php mysql`

Specs:
Devilbox 1.9.2 on macOS 11.6 with Docker Desktop 4.3.1.
Running macOS as *non* admin user.

Summary:
Everything else runs fine. Tried this in the container but didn't help, would be overwritten anyway after stopping/removing container: https://stackoverflow.com/a/58950678
Thanks!

**Comment by BleddP** [comment]
I have the same issue, wondering if it might have something to do with Docker and support for Apple silicon as I am running on a 14" Macbook Pro with M1 Pro chip. 

You can also run `docker composer up httpd php mysql -d` to run it in the background if the warning bothers you.

Either way would be nice to hear what the fix is as I am also not sure

**Comment by zaarheed** [comment]
Also an issue for me on a new Appe silicon M1 MacBook. The same files and config don't report this warning on a 2014 rMBP

**Comment by onasipim** [comment]
Yes, I'm also running on a Macbook Air with M1 chip

**Comment by nicolaspennesi** [comment]
I having this issue on MacBoom M1 Pro too.

**Comment by olliefwilliams** [comment]
I'm also having the same issue, and also running a M1 Macbook Pro.

**Comment by cytopia** [comment]
@onasipim this is just a warning and should not affect anything. Simply ignore it as I have not seen any functionality that was broken by this. I'm going to close this issue. If you encounter anything which is not working due to this warning, please clarify.

**Comment by guycalledseven** [comment]
@cytopia Can we please reopen this issue? I can submit PR but don't know where. I think the fix is pretty easy.

While running on M1 Macbook Pro, `pidof` in container(s) does not return anything for any running process if the image is not ARM64, because every program is being run by `qemu-x86_6`. 

When I bash into my running php7.4 container I **see running rsyslogd** and eg. php-fpm but like this:

```
root      4148  0.1  1.1 692572 93892 ?        Sl   20:36   0:00 /usr/bin/qemu-x86_64 /usr/local/sbin/php-fpm
root      4146  0.1  0.2 298752 16436 ?        Sl   20:36   0:00 /usr/bin/qemu-x86_64 /usr/sbin/rsyslogd -n
```

The `pidof` does not return anything for eg rsyslogd

```
root@php-7.4.27 in /shared/httpd $ pidof rsyslogd
root@php-7.4.27 in /shared/httpd $ pidof php-fpm
root@php-7.4.27 in /shared/httpd $ pidof qemu-x86_64
12756 12754 10440 7419 7416 7415 7413 7127 4168 4164 4162 4158 4156 4154 4150 4148 4146 1
```

But actually pgrep - does:

```
root@php-7.4.27 in /shared/httpd $ pgrep -f rsyslogd
4146
root@php-7.4.27 in /shared/httpd $ pgrep -f php-fpm
4148
```

The solution to stop the logs is to bash into php container and change `/usr/local/sbin/postfix.sh` 

```
if ! pidof rsyslogd >/dev/null 2>&1; then
```
to 

```
if ! pgrep rsyslogd >/dev/null 2>&1; then
```

**Comment by cytopia** [comment]
@guycalledseven looks legit. Will re-open and prepare something for you to test out.

**Comment by cytopia** [comment]
Fixed here: https://github.com/cytopia/devilbox/releases/tag/v1.11.0
