### ISSUE TITLE
Make Images support arm64 natively for development on M1 Macs

### ISSUE THREAD

**Issue by aliz7** [cytopia/devilbox#855]
#### ISSUE TYPE

 - Feature request

#### SUMMARY
Hi,

I'm using a MacBook Pro 2021 with M1 Pro ARM CPU. Unfortunately, the custom devilbox docker images do not support arm64 natively whereas all the official httpd, php, mariadb etc. images already support arm64 natively.

#### Goal
Make Images support arm64 natively for development on M1 Macs

**Comment by cytopia** [comment]
I was looking into building ARM images. This however seems to be rather problematic. I have currently tested it with a base image (PHP 8.2) in this PR: https://github.com/devilbox/docker-php-fpm-8.2/pull/2

* **AMD64** image builds in about **9 minutes** (as it did in single run before)
* **ARM64** image builds in about **100 minutes** (more than factor 11 longer)

Timewise it would all be do-able for the used Docker images for Devilbox, however, when looking at the actual PHP images, the fastest pipeline was 1 hours. When doing ARM64 images the pipeline will most likely also be (more than) 11 times slower, which would result into something like at least **11 hours** per build.

As far as I've read, GitHub actions allows a maximum of **6 hours** per job, so that would be currently impossible.

Additionally, as this is only a non-commercial project I'm doing in my spare-time and migrating, testing and fixing tens of docker images would take months and lots of energey, it is something which I'm unable take. I will leave this to the community.

If somebody wants to step in and take action and is also able to solve the long-running pipelines, then let me know and we can work something out.

**Comment by cytopia** [comment]
## Update

I have added two more required base images to support arm64 on Debian Jessie:
* https://github.com/devilbox/docker-php-fpm-5.4 (base image only)
* https://github.com/devilbox/docker-php-fpm-5.5 (base image only)

**Comment by joeke** [comment]
@cytopia Not sure if I understand correctly, but to be able to use this on an M1 Mac I can only use one of the PHP base images? So in my docker-compose I cannot use for example `devilbox/php-fpm:${PHP_SERVER}-work-0.136` but can only use the base PHP image (i.e. `devilbox/php-fpm-8.0`) but then I'd have to load php modules etc. manually?

**Comment by cytopia** [comment]
> @cytopia Not sure if I understand correctly, but to be able to use this on an M1 Mac I can only use one of the PHP base images?

@joeke no, the base images cannot be used for the Devilbox. They are however a requirement to eventually build the Devilbox images.

**Comment by cytopia** [comment]
## Update

Finally full `arm64` support has been released: https://github.com/cytopia/devilbox/releases/tag/v2.1.0

@frumbert @Lenitr @mhodge13 @boumanb @joeke could you guys give some updates on how this is working, as I don't have an arm64 machine myself

**Comment by joeke** [comment]
@cytopia Awesome, thank you! I'll give it a test on my Macbook and let you know how it goes.

**Comment by joeke** [comment]
@cytopia Looks to be working as expected from my end. I've used the bind, httpd (nginx), mysql and php (8.1 and 7.4) containers and they all work fine. Also working in the shell of the PHP containers looks good; I've used the node, npm, nvm and composer scripts inside the containers and those seem to be working fine as well.
So in short; looks to be working on M1 Mac!

**Comment by howdu** [comment]
Still no official support from Mailhog but there's a brilliant fork from [jcalonso/MailHog](https://github.com/jcalonso/MailHog) which does.

https://github.com/mailhog/MailHog/issues/359#issuecomment-1107160980
