### ISSUE TITLE
[Howto]: Run Devilbox with PHP as apache module

### ISSUE THREAD

**Issue by paddelboot** [cytopia/devilbox#909]
### Have you already checked elsewhere?

- [X] I have read the [Devilbox documentation](https://devilbox.readthedocs.io/en/latest/)
- [X] I have checked the [Devilbox Troubleshooting Guide](https://devilbox.readthedocs.io/en/latest/)
- [X] I have checked the [Devilbox FAQ](https://devilbox.readthedocs.io/en/latest/support/faq.html)
- [X] I have checked the [Devilbox Howto](https://devilbox.readthedocs.io/en/latest/support/howto.html)
- [X] I have checked the [Devilbox Forum](https://devilbox.discourse.group/)
- [X] I have checked [existing issues](https://github.com/cytopia/devilbox/issues)
- [X] I have googled already with no luck
- [ ] I have not done any of the above

### What are you struggling with?

Run PHP as apache module so I can model the environment on my client's server.

### What have you tried already?

All of the above checkboxes.

### What is your goal?

To run Devilbox with PHP as apache module

**Comment by cytopia** [comment]
This is not goint to work as PHP is not available on the Apache Docker image. PHP has been split out into separate images in order to allow for an easy switch of PHP versions.

**Why:** If I had to add it to the Apache image, then I would need to create as many different Apache images (for 2.2 and 2.4) as PHP versions are available. And also somehow do the same for Nginx.
