### ISSUE TITLE
Devilbox for android

### ISSUE THREAD

**Issue by zsyborg** [cytopia/devilbox#937]
### What is your idea or feature suggestion?

There are 2 good web server apps for Android. Bitwebserver and Ksweb server. Devil box has more features than the above-mentioned apps. It would be great is we ported DevilBox for android.

### Benefits

> Can be useful for developers to develop on the mobile device itself

> Will be more popular and gain users around the globe as Devilbox has more compatibie databases than its competitors 

### Are you willing to provide a PR to address this?

No

**Comment by cytopia** [comment]
I would question the benefit to "develop" on a phone where you can barely type. Besides, Devilbox has a pretty high storage and memory footprint relative to what is nowadays available on mobiles. 

> It would be great is we ported DevilBox for android.

Devilbox uses Docker and Docker Compose and supports `amd64` and `arm64` architectures only (see requirements). If these work on android, then you might be able to run it, otherwise you will be out of luck.

You can start here: https://gist.github.com/arno01/ebf570af208e28c1a0cf78da4f63bc9c and see if you can get something together, but there is not going to be any official support for this atm.
